version: "3"

services:

  # Drupal Database
  drupal_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: drupal_db
    ports:
      - "33061:3306"
    restart: unless-stopped
    volumes:
      - drupal_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    networks:
      - drupal

  # WordPress Database
  wordpress_db:
    image: mysql:8.0
    volumes:
      - wordpress_db_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress

  # Drupal
  drupal:
    image: drupal:9-php7.4-apache
    container_name: drupal
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./drupal/d_modules:/var/www/html/modules \
      - ./drupal/d_profiles:/var/www/html/profiles \
      - ./drupal/d_sites:/var/www/html/sites \
      - ./drupal/d_themes:/var/www/html/themes \
      - ./scripts/drush:/opt/drupal/scripts
    depends_on:
      - drupal_db
    environment:
      HOST: drupal_db:33061
      DBASE: drupal
      USER: drupal
      PASS: drupal
      DATABASE_HOST: drupal_db:33061
    env_file:
      - drupal-install.env
    links:
      - drupal_db:mysql
    networks:
      - drupal
  # WordPress
  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: [ './wordpress/:/var/www/html' ]
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wordpress

volumes:
  drupal_db_data: {}
  drupal_data: {}
  wordpress_db_data: {}

networks:
  drupal:
  wordpress:
