version: "3"

services:

  # Database
  drupal_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: drupal_db
    ports:
      - "33061:3306"
    restart: unless-stopped
    volumes:
      - drupal_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    networks:
      - drupal

  # Drupal
  drupal:
    image: drupal:9-php7.4-apache
    container_name: drupal
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./drupal/d_modules:/var/www/html/modules \
      - ./drupal/d_profiles:/var/www/html/profiles \
      - ./drupal/d_sites:/var/www/html/sites \
      - ./drupal/d_themes:/var/www/html/themes \
    depends_on:
      - drupal_db
    environment:
      HOST: drupal_db:33061
      DBASE: drupal
      USER: drupal
      PASS: drupal
      DATABASE_HOST: drupal_db:33061
    links:
      - drupal_db:mysql
    networks:
      - drupal

volumes:
  drupal_db_data: {}
  drupal_data: {}
  wordpress_db_data: {}

networks:
  drupal:
  wordpress:
